"""Render the pipeline's held-out results into a Markdown report.

The pipeline logs everything to MLflow, but MLflow is a local store reviewers
cannot see on GitHub. This module renders the same numbers into a single
committed Markdown file (``docs/RESULTS.md`` by default) so the README can carry
a short summary and link to the full, regenerated report instead of hard-coding
metrics that silently drift out of date.

``render_results_markdown`` is a pure function (dict in, string out) so it is
unit-testable without running the pipeline; the pipeline owns writing the file.
"""

from __future__ import annotations

import subprocess
from datetime import datetime, timezone

import pandas as pd

# Column labels for the cross-validated comparison table, matched by prefix to
# whatever numeric columns compare_models happens to emit.
_GENERATED_NOTE = (
    "_This file is generated by `churn-pipeline` (see "
    "[README](../README.md#latest-local-results)); re-run the pipeline to refresh "
    "it. Do not edit by hand._"
)


def git_commit_short(project_root: str) -> str | None:
    """Best-effort short git SHA of the working tree; ``None`` if unavailable."""
    try:
        out = subprocess.run(
            ["git", "-C", project_root, "rev-parse", "--short", "HEAD"],
            capture_output=True, text=True, timeout=5, check=True,
        )
        return out.stdout.strip() or None
    except (subprocess.SubprocessError, OSError):
        return None


def _fmt(value, digits: int = 3) -> str:
    """Format a float to fixed digits, pass through everything else as ``str``."""
    if isinstance(value, float):
        return f"{value:.{digits}f}"
    return str(value)


def render_results_markdown(results: dict) -> str:
    """Render a results dict into a Markdown report string.

    Expected keys (all optional except ``model`` and the metric dicts): ``model``,
    ``run_id``, ``git_commit``, ``timestamp`` (ISO string), ``dataset`` (dict:
    ``raw_rows``, ``clean_rows``, ``churn_rate``, ``target``), ``test_rows``,
    ``test_pos``, ``test_neg``, ``threshold``, ``fn_fp_ratio``, ``ranking`` (dict),
    ``operating`` (dict with confusion counts), ``test_cost``, ``brier``, ``ece``,
    ``brier_oof``, ``ece_oof``, ``cv_stats`` (dict metric -> (mean, std)),
    ``comparison`` (DataFrame or None), ``importance`` (DataFrame or None).
    """
    r = results
    lines: list[str] = ["# Latest Local Results", "", _GENERATED_NOTE, ""]

    # --- Provenance ---
    lines += ["## Run provenance", "", "| Field | Value |", "|---|---|"]
    prov = [
        ("Run date (UTC)", r.get("timestamp")),
        ("Model", r.get("model")),
        ("Git commit", r.get("git_commit")),
        ("MLflow run ID", r.get("run_id")),
    ]
    ds = r.get("dataset") or {}
    if ds:
        churn = ds.get("churn_rate")
        prov += [
            ("Raw rows", ds.get("raw_rows")),
            ("Rows after dedup", ds.get("clean_rows")),
            ("Churn rate", f"{churn:.1%}" if isinstance(churn, float) else churn),
            ("Target column", f"`{ds.get('target')}`" if ds.get("target") else None),
        ]
    if r.get("test_rows") is not None:
        prov.append((
            "Test split size",
            f"{r['test_rows']} rows ({r.get('test_pos', '?')} churners, "
            f"{r.get('test_neg', '?')} non-churners)",
        ))
    for label, value in prov:
        if value is not None:
            lines.append(f"| {label} | {value} |")
    lines.append("")

    # --- Held-out test metrics ---
    ranking = r.get("ranking") or {}
    op = r.get("operating") or {}
    thr = r.get("threshold")
    lines += [
        f"## Held-out test results ({r.get('model', 'final model')})", "",
        "| Metric | Value |", "|---|---:|",
    ]
    if "pr_auc" in ranking:
        lines.append(f"| Test PR-AUC | {ranking['pr_auc']:.3f} |")
    if "roc_auc" in ranking:
        lines.append(f"| Test ROC-AUC | {ranking['roc_auc']:.3f} |")
    thr_lbl = f" @ threshold {thr:.3f}" if isinstance(thr, float) else ""
    for name, key in (("Precision", "precision"), ("Recall", "recall"), ("F1", "f1")):
        if key in op:
            lines.append(f"| {name}{thr_lbl} | {op[key]:.3f} |")
    if all(k in op for k in ("tp", "fp", "fn", "tn")):
        lines.append(
            f"| Confusion matrix | TP={op['tp']}, FP={op['fp']}, "
            f"FN={op['fn']}, TN={op['tn']} |"
        )
    if r.get("test_cost") is not None:
        ratio = r.get("fn_fp_ratio", 10)
        lines.append(
            f"| Business cost (`{_fmt(ratio, 0)} * FN + FP`) | "
            f"{r['test_cost']:.0f} FP-equivalents |"
        )
    if r.get("brier") is not None:
        lines.append(f"| Calibration Brier / ECE (test) | "
                     f"{r['brier']:.4f} / {r['ece']:.4f} |")
    if r.get("brier_oof") is not None:
        lines.append(f"| Calibration Brier / ECE (OOF) | "
                     f"{r['brier_oof']:.4f} / {r['ece_oof']:.4f} |")
    lines.append("")

    # --- Cross-validated model comparison ---
    comparison = r.get("comparison")
    if comparison is not None and not comparison.empty:
        lines += ["## Cross-validated model comparison", ""]
        lines += _df_to_md(comparison)
        lines.append("")

    # --- Permutation importance ---
    importance = r.get("importance")
    if importance is not None and not importance.empty:
        top = importance.head(10)
        lines += [
            "## Top permutation-importance drivers (test PR-AUC drop)", "",
            "| Feature | PR-AUC drop |", "|---|---:|",
        ]
        for _, row in top.iterrows():
            lines.append(f"| `{row['feature']}` | {row['importance_mean']:.3f} |")
        lines += [
            "",
            "These are permutation importances on the held-out test split — this "
            "model's predictive reliance, not a causal estimate of what reduces churn.",
        ]
        lines.append("")

    lines += [
        "---",
        "",
        "These are offline validation results on a static local dataset, not "
        "production performance guarantees.",
        "",
    ]
    return "\n".join(lines)


def _df_to_md(df: pd.DataFrame) -> list[str]:
    """Render a DataFrame as GitHub-flavored Markdown table rows."""
    cols = list(df.columns)
    header = "| " + " | ".join(str(c) for c in cols) + " |"
    sep = "|" + "|".join("---" for _ in cols) + "|"
    rows = [header, sep]
    for _, row in df.iterrows():
        cells = [_fmt(row[c]) for c in cols]
        rows.append("| " + " | ".join(cells) + " |")
    return rows


def default_timestamp() -> str:
    """Current UTC timestamp as a compact ISO-ish string for the report header."""
    return datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
